
env:
  AWS_REGION: eu-north-1
  S3_BUCKET: githubaction-demo-1

name: Upload Large Files to S3

on:
  push:
    branches:
    - master
    paths:
      - 'large-files/**'

env:
  AWS_REGION: eu-north-1
  S3_BUCKET: githubaction-demo-1
  MULTIPART_THRESHOLD: '50MB'  # Switch to multipart above this size
  MULTIPART_CHUNKSIZE: '25MB'  # Size of each part

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI with large file support
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Upload files with proper content-length handling
        run: |
          # Function to upload with proper headers
          upload_file() {
            local file_path=$1
            local file_size=$(stat -c%s "$file_path")
            local s3_path="s3://${{ env.S3_BUCKET }}/${file_path#large-files/}"

            echo "Uploading $file_path (Size: $file_size bytes)"

            if [ "$file_size" -gt 52428800 ]; then  # 50MB in bytes
              echo "Using multipart upload for large file"
              aws s3 cp "$file_path" "$s3_path" \
                --content-length "$file_size" \
                --expected-size "$file_size" \
                --multipart-chunksize ${{ env.MULTIPART_CHUNKSIZE }} \
                --metadata "UploadMethod=multipart"
            else
              echo "Using standard upload"
              aws s3 cp "$file_path" "$s3_path" \
                --content-length "$file_size" \
                --metadata "UploadMethod=standard"
            fi
          }

          # Find and upload all files
          find large-files/ -type f | while read file; do
            upload_file "$file" || exit 1
          done

      - name: Verify uploads
        run: |
          aws s3 ls --recursive s3://${{ env.S3_BUCKET }} \
            --human-readable \
            --summarize
